//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAudioSwitcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoAudioSwitcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TrayIconDark {
            get {
                object obj = ResourceManager.GetObject("TrayIconDark", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TrayIconLight {
            get {
                object obj = ResourceManager.GetObject("TrayIconLight", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TrayIconDarkDisabled {
            get {
                object obj = ResourceManager.GetObject("TrayIconDarkDisabled", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TrayIconLightDisabled {
            get {
                object obj = ResourceManager.GetObject("TrayIconLightDisabled", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to (Don&apos;t switch).
        /// </summary>
        internal static string EmptyStringMenuItem {
            get {
                return ResourceManager.GetString("EmptyStringMenuItem", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Settings….
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Auto Audio Switcher.
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception..
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Open log directory.
        /// </summary>
        internal static string OpenLogDirectory {
            get {
                return ResourceManager.GetString("OpenLogDirectory", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Browse….
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Monitors.
        /// </summary>
        internal static string Monitors {
            get {
                return ResourceManager.GetString("Monitors", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Switching mode.
        /// </summary>
        internal static string RoutingModeGroup {
            get {
                return ResourceManager.GetString("RoutingModeGroup", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Follow the focused window (global).
        /// </summary>
        internal static string RoutingModeGlobal {
            get {
                return ResourceManager.GetString("RoutingModeGlobal", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Audio follows the monitor of whichever window currently has focus. Every application shares one d....
        /// </summary>
        internal static string RoutingModeGlobalDescription {
            get {
                return ResourceManager.GetString("RoutingModeGlobalDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Follow each window (per application).
        /// </summary>
        internal static string RoutingModePerApp {
            get {
                return ResourceManager.GetString("RoutingModePerApp", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Each application playing audio is routed to the device assigned to the monitor its own window is ....
        /// </summary>
        internal static string RoutingModePerAppDescription {
            get {
                return ResourceManager.GetString("RoutingModePerAppDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Per-application routing is unavailable on this system (no usable audio policy interface was found)..
        /// </summary>
        internal static string RoutingModePerAppUnavailable {
            get {
                return ResourceManager.GetString("RoutingModePerAppUnavailable", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Enable auto-switching.
        /// </summary>
        internal static string EnableSwitching {
            get {
                return ResourceManager.GetString("EnableSwitching", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Start automatically when I sign in.
        /// </summary>
        internal static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Follow system.
        /// </summary>
        internal static string LanguageSystem {
            get {
                return ResourceManager.GetString("LanguageSystem", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Language changes take effect after restarting the program..
        /// </summary>
        internal static string LanguageRestartRequired {
            get {
                return ResourceManager.GetString("LanguageRestartRequired", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Log level.
        /// </summary>
        internal static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Debug (verbose).
        /// </summary>
        internal static string LogLevelDebug {
            get {
                return ResourceManager.GetString("LogLevelDebug", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string LogLevelInformation {
            get {
                return ResourceManager.GetString("LogLevelInformation", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string LogLevelWarning {
            get {
                return ResourceManager.GetString("LogLevelWarning", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Error (default).
        /// </summary>
        internal static string LogLevelError {
            get {
                return ResourceManager.GetString("LogLevelError", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Open log directory.
        /// </summary>
        internal static string OpenLogDirectoryButton {
            get {
                return ResourceManager.GetString("OpenLogDirectoryButton", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Choose a playback device for each monitor. In per-application mode this decides where each applic....
        /// </summary>
        internal static string MonitorMappingDescription {
            get {
                return ResourceManager.GetString("MonitorMappingDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string ColumnMonitor {
            get {
                return ResourceManager.GetString("ColumnMonitor", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Playback device.
        /// </summary>
        internal static string ColumnPlaybackDevice {
            get {
                return ResourceManager.GetString("ColumnPlaybackDevice", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to No monitors detected..
        /// </summary>
        internal static string NoMonitorsDetected {
            get {
                return ResourceManager.GetString("NoMonitorsDetected", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to (Don&apos;t switch).
        /// </summary>
        internal static string DontSwitch {
            get {
                return ResourceManager.GetString("DontSwitch", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to (device not connected: {0}).
        /// </summary>
        internal static string PlaybackDeviceNotFound {
            get {
                return ResourceManager.GetString("PlaybackDeviceNotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to {0} monitor(s) have no playback device selected....
        /// </summary>
        internal static string UnconfiguredMonitorsWarning {
            get {
                return ResourceManager.GetString("UnconfiguredMonitorsWarning", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to {0} - not configured.
        /// </summary>
        internal static string UnconfiguredMonitorCell {
            get {
                return ResourceManager.GetString("UnconfiguredMonitorCell", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        internal static string CheckForUpdatesOnStartup {
            get {
                return ResourceManager.GetString("CheckForUpdatesOnStartup", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Check now.
        /// </summary>
        internal static string CheckNow {
            get {
                return ResourceManager.GetString("CheckNow", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Current version: {0}.
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates….
        /// </summary>
        internal static string UpdateChecking {
            get {
                return ResourceManager.GetString("UpdateChecking", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re up to date..
        /// </summary>
        internal static string UpdateUpToDate {
            get {
                return ResourceManager.GetString("UpdateUpToDate", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is available (you have {1})..
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}….
        /// </summary>
        internal static string UpdateDownloading {
            get {
                return ResourceManager.GetString("UpdateDownloading", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to The update has been downloaded. The program will restart to finish installing..
        /// </summary>
        internal static string UpdateReadyToInstall {
            get {
                return ResourceManager.GetString("UpdateReadyToInstall", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Could not check for updates: {0}.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Automatic updates are not supported for this installation. Please download the new version from t....
        /// </summary>
        internal static string UpdateNotSupported {
            get {
                return ResourceManager.GetString("UpdateNotSupported", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Update now.
        /// </summary>
        internal static string UpdateInstallNow {
            get {
                return ResourceManager.GetString("UpdateInstallNow", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string UpdateInstallLater {
            get {
                return ResourceManager.GetString("UpdateInstallLater", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new:.
        /// </summary>
        internal static string UpdateReleaseNotes {
            get {
                return ResourceManager.GetString("UpdateReleaseNotes", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Open releases page.
        /// </summary>
        internal static string OpenReleasesPage {
            get {
                return ResourceManager.GetString("OpenReleasesPage", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Switches the default playback device based on the monitor a window is on..
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Released under the Apache License, Version 2.0..
        /// </summary>
        internal static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Based on Auto Audio Switcher by Max Kagamine..
        /// </summary>
        internal static string AboutBasedOn {
            get {
                return ResourceManager.GetString("AboutBasedOn", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Open project page.
        /// </summary>
        internal static string OpenSourcePage {
            get {
                return ResourceManager.GetString("OpenSourcePage", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string BalloonUpdateAvailableTitle {
            get {
                return ResourceManager.GetString("BalloonUpdateAvailableTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Auto Audio Switcher {0} is available. Click to see the details..
        /// </summary>
        internal static string BalloonUpdateAvailableText {
            get {
                return ResourceManager.GetString("BalloonUpdateAvailableText", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        internal static string BalloonSettingsSaved {
            get {
                return ResourceManager.GetString("BalloonSettingsSaved", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Failed to save settings..
        /// </summary>
        internal static string ErrorSavingSettings {
            get {
                return ResourceManager.GetString("ErrorSavingSettings", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Auto Audio Switcher.
        /// </summary>
        internal static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
    }
}
